# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/1a37ffe9-19af-48d4-a014-cb109e1b0cb8/transcription
Content-Type: application/json

{
    "prompt": "bom dia, meme whatsapp"
}