# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/d9ca414c-4934-4a1d-9649-3824a02b2eaf/transcription
Content-Type: application/json

{
    "prompt": "mesagem de boa tarde, meme, quero comprar cuscuz"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "d9ca414c-4934-4a1d-9649-3824a02b2eaf",
    "temperature": 0.5,
    "template": "gere um resumo do que aconteceu na transcrição do vídeo informado a seguir: '''{transcription}'''"
}